-- ============================================================
-- Tabla COMPARTIDA de proveedores
-- Usada por el Centro de Control (Presupuestos → Base de Datos)
-- y por el Comparativo (Proveedores & PDFs → Base de Datos).
-- Ejecutar en Supabase → SQL Editor. Es idempotente (se puede correr varias veces).
-- ============================================================

-- 1) Crear la tabla si no existe
create table if not exists public.proveedores (
  id              bigint generated by default as identity primary key,
  nombre          text not null,
  cuit            text,
  rubro           text,
  email           text,
  tel             text,        -- TELÉFONO
  direccion       text,
  contacto        text,        -- CONTACTO
  condicion_pago  text,
  tipo            text,
  created_at      timestamptz default now()
);

-- 2) Asegurar TODAS las columnas (por si la tabla ya existía con menos campos)
alter table public.proveedores add column if not exists nombre          text;
alter table public.proveedores add column if not exists cuit            text;  -- CUIT
alter table public.proveedores add column if not exists rubro           text;
alter table public.proveedores add column if not exists email           text;  -- EMAIL
alter table public.proveedores add column if not exists tel             text;  -- TELÉFONO
alter table public.proveedores add column if not exists direccion       text;
alter table public.proveedores add column if not exists contacto        text;  -- CONTACTO
alter table public.proveedores add column if not exists condicion_pago  text;
alter table public.proveedores add column if not exists tipo            text;
alter table public.proveedores add column if not exists created_at      timestamptz default now();

-- 3) (Opcional pero recomendado) evitar proveedores duplicados por nombre.
--    El upsert de ambos tableros usa el NOMBRE como clave, así que conviene un índice único.
--    Si este paso falla por duplicados previos, ejecutá primero el bloque de de-duplicado de abajo.
create unique index if not exists proveedores_nombre_uidx on public.proveedores (nombre);

-- 3b) De-duplicado previo (ejecutar SOLO si el paso 3 dio error por duplicados):
-- delete from public.proveedores a
-- using public.proveedores b
-- where a.id > b.id and upper(a.nombre) = upper(b.nombre);
-- (luego volver a ejecutar el create unique index del paso 3)

-- 4) Permisos (RLS) — permitir lectura/escritura con la anon key que usan los tableros.
--    Si la tabla ya venía funcionando con los tableros, estas políticas probablemente ya existen.
alter table public.proveedores enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where tablename='proveedores' and policyname='proveedores_select_anon') then
    create policy proveedores_select_anon on public.proveedores for select using (true);
  end if;
  if not exists (select 1 from pg_policies where tablename='proveedores' and policyname='proveedores_insert_anon') then
    create policy proveedores_insert_anon on public.proveedores for insert with check (true);
  end if;
  if not exists (select 1 from pg_policies where tablename='proveedores' and policyname='proveedores_update_anon') then
    create policy proveedores_update_anon on public.proveedores for update using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where tablename='proveedores' and policyname='proveedores_delete_anon') then
    create policy proveedores_delete_anon on public.proveedores for delete using (true);
  end if;
end $$;
