-- ════════════════════════════════════════════════════════════════
-- TABLA 'comparativas' — Historial de CCP + Ahorro Generado (Centro de Control)
-- Ejecutar una vez en Supabase → SQL Editor → New query → Run.
-- Es idempotente: se puede correr varias veces sin romper nada.
-- ════════════════════════════════════════════════════════════════

create table if not exists public.comparativas (
  id bigint generated by default as identity primary key,
  creado_at timestamptz default now()
);

-- Columnas que usa la app (no falla si ya existen)
alter table public.comparativas add column if not exists num_comp          text;
alter table public.comparativas add column if not exists num_sc            text;
alter table public.comparativas add column if not exists asunto            text;
alter table public.comparativas add column if not exists solicitante       text;
alter table public.comparativas add column if not exists area              text;
alter table public.comparativas add column if not exists divisa            text;
alter table public.comparativas add column if not exists fecha             date;
alter table public.comparativas add column if not exists observaciones     text;
alter table public.comparativas add column if not exists items             text;
alter table public.comparativas add column if not exists proveedores       text;
alter table public.comparativas add column if not exists analisis          text;
alter table public.comparativas add column if not exists proveedor_elegido text;
alter table public.comparativas add column if not exists precio_elegido    double precision;
alter table public.comparativas add column if not exists precio_max        double precision;
alter table public.comparativas add column if not exists ahorro            double precision;
alter table public.comparativas add column if not exists estado            text;
alter table public.comparativas add column if not exists origen            text;
alter table public.comparativas add column if not exists autorizado_en     text;

-- ÍNDICE útil para ordenar por fecha de creación
create index if not exists comparativas_creado_idx on public.comparativas (creado_at desc);

-- ════════════════════════════════════════════════════════════════
-- RLS: permitir lectura y escritura con la API key pública (anon),
-- igual que el resto de las tablas de la app. SIN esto, las lecturas
-- devuelven vacío y los guardados fallan en silencio.
-- ════════════════════════════════════════════════════════════════
alter table public.comparativas enable row level security;

drop policy if exists "comparativas_anon_all" on public.comparativas;
create policy "comparativas_anon_all" on public.comparativas
  for all
  to anon
  using (true)
  with check (true);
